### ISSUE TITLE
Make Sjiraffenvers stable

### ISSUE THREAD

**Issue by OverAss** [mannhullet/mannhullet_no#13]
Sjiraffenversgeneratoren (mannhullet.no/public/sjiraff) har slitt med at den blir spammet av bots, generelt russisk viagra og andre ymse saker. Dette gjør at JSON-filen med alle sjiraffenversene blir for overfylt og slutter å virke. Vi må finne en løsning på dette problemet. Om det består av å manuelt kontrollere alle innsendte vers eller en annen fiffig løsning er opp til oss.

**Comment by andrebk** [comment]
Foreslår å flytte hele greia inn under mannhullet.no application, i stedet for å ha det som en standalone greie. Ved å kreve brukeren å være innlogget for å kunne sende inn (men ikke for å lese) vers så burde vi unngå det meste av spam. Gir også muligheten til å implementere det med databasen, i stedet for den sykt hacka "les JSON fil inn i HTML dokument" løsningen vi har nå.

**Comment by OverAss** [comment]
Det høres ut som en veldig grei løsning på hele problemet. Da blir det at
vi får en tabell i databasen der hver rad er ett innlegg?
